### ISSUE TITLE
Add section for weekly IRC meetings

### ISSUE THREAD

**Issue by btcdrak** [bitcoin-core/website#18]

**Comment by harding** [comment]
I thought we were going to put that on Bitcoin.org?  https://github.com/bitcoin-dot-org/bitcoin.org/issues/1147

**Comment by btcdrak** [comment]
Yes, but that was before the decision to establish a separate website for the Bitcoin Core project. Since the meetings are specifically about Bitcoin Core project development, they belong on this site.

**Comment by luke-jr** [comment]
The meetings *are not* specifically about Bitcoin Core, and are explicitly about Bitcoin *in general*.

**Comment by btcdrak** [comment]
@luke-jr Well so far the topics discussed have only been about Core's ongoing pull requests, issues and release schedules.

**Comment by laanwj** [comment]
While I have tried to keep the discussion at a more abstract level, about bitcoin-essential topics such as BIPs and their implementation, releases and larger issues, not general programming or C++ ones, so it may be interesting for non-developer audience, the topics are primarily about Bitcoin Core, not other implementations. 

Some topics (such as BIPs and planned softforks) may affect other implementations as well, but the meeting is not limited to those.

I'm not sure what a general bitcoin developer meeting would be like, but I think it'd need a much more structured framework to avoid the kind of noise that almost killed the -dev mailing list. It's not what was my goal in any case.

**Comment by btcdrak** [comment]
Closed in 1446169
