### ISSUE TITLE
ACKs on the site?

### ISSUE THREAD

**Issue by narula** [bitcoin-core/website#19]
Happy to see this website!

Could you consider adding a list of people who ACK the website and a system for people to add/remove themselves to this list?  Like what was done for this post:

https://github.com/bitcoin-dot-org/bitcoin.org/pull/1165

Or perhaps even do so for each page/post on the site.

**Comment by btcdrak** [comment]
@narula thanks for the suggestion. We certainly do need a catchment area for roadmap signatures and it would make sense for some other things too where we need to update website content, for example if we add a page showing which wallets have segwit adoption on their roadmaps.

You are welcome to get involved in the review process on any pull request.

**Comment by laanwj** [comment]
I don't know. It is usually changes (github pull requests) that are ACKed, not so much pages itself. In most cases it's an informal way to assess if other people agree with a change or not.

The page that you reference is different - as it is a statement that may be controversial to some people, the list of names is a list of signatures of people that agree with it.

The rest of the site is not meant to be a list of controversial statements but e.g. documentation and blogs about larger projects that people are working on. So I'm not sure that a list of ACKs on the site is helpful. It's always possible to look at git history, at the pull requests on github, to see who is the author and who commented on the change.

**Comment by btcdrak** [comment]
@laanwj There are a couple of cases I can think where it would be useful administratively. I intend putting up a "who will add segwit support to their wallet/service" page to show which wallets are on board. After the page is merged, more wallet vendors could add their ACK to let us know of their support and we can add it. It could help administratively compared to what I am doing at the moment which is reaching out manually and recording support manually in a spreadsheet. We can use this sparingly when it is appropriate, which I agree is not likely to be that often..

**Comment by btcdrak** [comment]
@narula Thanks for the suggestions, I'll close this ticket now.
