### ISSUE TITLE
clarify against bitcoin.org

### ISSUE THREAD

**Issue by ethers** [bitcoin-core/website#22]
Please clarify bitcoin.org's private ownership
Maybe do so in "About" section

Is bitcoin.org owned by the Bitcoin Foundation?

**Comment by btcdrak** [comment]
You have the wrong repository. Please direct your questions to bitcoin.org's source repository github.com/bitcoin-dot-org/bitcoin.org

**Comment by ethers** [comment]
This suggestion is intended for this repo, because some more explanation of why bitcoincore.org should be preferred over the "incumbent" bitcoin.org, would help.  This can help #50

**Comment by MarcoFalke** [comment]
> preferred

None of them should be "preferred". Both host different content eventually. Bitcoin.org is for general education about Bitcoin and BitcoinCore.org is about developer stuff and Bitcoin Core.

**Comment by btcdrak** [comment]
@ethers bitcoin.org is a general website about Bitcoin.
bitcoincore.org is the project website for the Bitcoin Core project.
