### ISSUE TITLE
Language dropdown display issues after #28

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/website#46]
Looks like the language dropdown needs an update after #28. Sometimes it shows only English.

**Comment by stanfieldr** [comment]
I believe this is actually related to some of the pages not being translated yet.

**Comment by btcdrak** [comment]
Correct: If a post does not have a translation, it will only show the English dropdown.

**Comment by MarcoFalke** [comment]
Can't we just put the English text as placeholder for a translation?

I mean, it is really confusing to see two different websites when switching the language:

![screenshot from 2016-02-01 13-17-04](https://cloud.githubusercontent.com/assets/6399679/12717191/73186230-c8e6-11e5-993f-63775d9a84cd.png)
![screenshot from 2016-02-01 13-17-41](https://cloud.githubusercontent.com/assets/6399679/12717193/749c86b8-c8e6-11e5-9553-7c69f16009b2.png)

**Comment by btcdrak** [comment]
It just needs the translations to be made in `_data/navigation.yml` (and other navs to be sync'd up with the `en:`  tree).

**Comment by btcdrak** [comment]
I have pushed the current en: structure to the other languages.

**Comment by MarcoFalke** [comment]
Nice, c40eebb2c3084c045d3fbc25623a3da9bfa98ff9 fixed my issue.

**Comment by btcdrak** [comment]
Would you mind doing the German translation for those menus?
