### ISSUE TITLE
Information Cut off on Small Screens (mobile)

### ISSUE THREAD

**Issue by GIJensen** [bitcoin-core/website#63]
The page I noticed the issue is here: https://bitcoincore.org/en/segwit_wallet_dev/

The serialization format is cut off for me. An option to view the desktop version of the site would be helpful (like what Github has), scrolling left/right for those divs, or text wrapping.

BTW kudos to whoever wrote that, it looks pretty useful.

**Comment by btcdrak** [comment]
What mobile + browser version are you using? Any chance of a screenshot?

**Comment by GIJensen** [comment]
OS: Android 4.2.2
Browser: Opera Mini
Screenshot: http://fs5.directupload.net/images/160122/s8bd6et8.jpg

Opera Mini has two data savings modes, high and extreme. I tested both, I can copy the cut-off text (but not see it) on high, and I can't copy or see the text on extreme (To be expected, extreme is a bit weird).

**Comment by jonasschnelli** [comment]
It's a common problem of `<pre>` (code) text on mobile. But you can scroll horizontal on the particular code snipped (check SS).

IMO current state is okay.

<img width="487" alt="bildschirmfoto 2016-01-25 um 15 15 06" src="https://cloud.githubusercontent.com/assets/178464/12553232/86457480-c376-11e5-9f2c-510470f47132.png">

**Comment by GIJensen** [comment]
Not sure why but I couldn't scroll horizontally before. Probably a local issue.
