### ISSUE TITLE
ToC overlaps with header navigation

### ISSUE THREAD

**Issue by dexX7** [bitcoin-core/website#68]
The ToC of the RBF FAQ overlaps with the header navigation, and it looks a bit messy this way in my opinion:

![overlap](https://cloud.githubusercontent.com/assets/5836089/12552155/3ea731b4-c370-11e5-9f83-9c32057446ce.png)

**Comment by btcdrak** [comment]
ping @jonasschnelli

**Comment by jonasschnelli** [comment]
I kina liked the overlapping. Looks like it's on a different z-layer.
But if other thinks its looking bad, I can fix it.

**Comment by MarcoFalke** [comment]
The reason it looks odd is because both the toc and the header are black toned.

**Comment by jonasschnelli** [comment]
It's gray on back?! Okay. Let me try to fix it.
