### ISSUE TITLE
Note that "bi-directional payment channels" are a proprietary unimplemented technology

### ISSUE THREAD

**Issue by Azulan** [bitcoin-core/website#7]
For the sake of intellectual honesty, the FAQ should explain that Blockstream, a private for profit company, is exerting monetary influence upon many core devs to support a payment network that they have a stake in, reducing privacy and enabling rent seeking behavior at the expense of bitcoin users, stakeholders and the community. The FAQ should also note that this influence is also discouraging exploration and implementations of simple, open and decentralized solutions such as increasing the block size to enable more individuals and businesses to participate in the bitcoin economy in a way that does not render them vulnerable to Blockstream's machinations and schemes.

**Comment by btcdrak** [comment]
Please stop brigading this tracker.
