### ISSUE TITLE
Core needs to distance itself from the attacks made "in its support"

### ISSUE THREAD

**Issue by dskloet** [bitcoin-core/website#75]
People are doing vile things, supposedly in support of Bitcoin Core. These attacks reflect very badly on Core. Some examples:

Censoring large forums to hide the existing of other teams/clients.
DDoS'ing Bitcoin XT nodes and pools.
DDoS'ing Coinbase.
Removing Coinbase from bitcoin.org

Since these things reflect very badly on the Core team, it would be good to have a public announcement, distancing the team from those attacks and discouraging those attacks since they are not helping anyone.

**Comment by kanzure** [comment]
Stop spamming this everywhere, you already posted https://github.com/bitcoin/bitcoin/issues/7406 and were told about an existing PR on the website repo. There's no reason for yet another opened issue.

**Comment by dskloet** [comment]
Don't be silly. I posted it there and was told this was the right place. This is not "yet another opened issue"; it's the replacement of the other issue that was closed.

The PR doesn't address the issue. It's way too vague and won't convince anyone. It doesn't call out any specific attacks. If Core actually thinks that r/bitcoin is too heavily moderated, it would suggest a better alternative. Otherwise this means nothing.

> At the same time, there is universal agreement to not engage in brigading, to reject participation in denial-of-service attacks, and to assume good faith in absence of reason to believe otherwise.

Really? Clearly there isn't because exactly those attacks do happen.

**Comment by NicolasDorier** [comment]
@dskloet comment on https://github.com/bitcoin-core/website/pull/58/files

**Comment by FrancisPouliot** [comment]
No, the core website does not need to do that IMO. Where do we stop? Do core devs need to distance themselves from all the vile things done using the software they contribute to too?

This is nonsense. Distancing from censorship is good, but this is going too far.

**Comment by rebroad** [comment]
@dskloet How can core distance themselves any more than they already have? If they were to reference the things you mention, that would be the opposite of distancing themselves, would it not?
