### ISSUE TITLE
opt-in RBF language about nlocktime

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-core/website#88]
"After all, the transaction has been explicitly marked as replaceable, and even without RBF, nLocktime may result in a conflict getting confirmed first."  

What is this getting at exactly?

**Comment by btcdrak** [comment]
I suggest discussing in #bitcoin-dev. However, to answer your question, the point is transactions can easily be trivially double-spent without RBF https://petertodd.org/2016/are-wallets-ready-for-rbf

**Comment by mably** [comment]
Is it possible to know who authored these documents exactly or not?  Should be simpler to be able to contact directly the right persons.

**Comment by btcdrak** [comment]
@ajtowns is the author (he's available on Slack as `@aj`

**Comment by mably** [comment]
Great, thanx @btcdrak!
